version: '3'
services:
  portfolio:
    build: .
    image: portfolio:dev
    container_name: portfolio
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules

